### PR TITLE
[pr2_gazebo_plugins] append gazebo CFLAGS

### PR DESCRIPTION
**Pull request by furushchev**
This fix is necessary for working with gazebo 6

### CODE REVIEW

**Comment by trainman419** [comment]
This should be done a per-target basis, not for the entire project.

Something like: `set_target_properties(<target> COMPILE_FLAGS ${GAZEBO_CXX_FLAGS});`

**Comment by furushchev** [comment]
@trainman419 Thank you for reviewing. I updated the commit.

**Comment by furushchev** [comment]
@trainman419 Any updates? Please merge if there is no problem.

**Comment by furushchev** [comment]
@trainman419 Thank you for merging!

**Pull request merged**
